version: '3.8'

services:
  backend:
    build: 
      dockerfile: ./compose/backend/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./model:/app/model
    depends_on:
      - db

  frontend:
    build: 
      dockerfile: ./compose/frontend/Dockerfile
      context: .
    restart: unless-stopped

  nginx:
    build: 
      dockerfile: ./compose/nginx/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
    volumes:
      - ./mounts/uwsgi:/uwsgi
      - ./mounts/logs/nginx:/var/log/nginx
      - ./mounts/media:/webapp/media:ro
      - ./mounts/static:/webapp/static:ro
